### PR TITLE
Dockerized the website. See README.md for instructions

### PR DESCRIPTION
**Pull request by repejota**
Build with `docker build -t barcelonajs .`

Run with `docker run -p 80:3000 -ti --rm -v `pwd`:/barcelonajs barcelonajs`

Go to http://<dockerip> 

Boom! :sunglasses:

### CODE REVIEW

**Comment by PatrickHeneise** [comment]
Merged. But why run docker if you can just `npm run dev` and everything works? 

Website is not hosted on a web server but on gh-pages.

**Comment by repejota** [comment]
I use docker because I do not have node on my laptop.

Yes, I know that it is hosted on gh-pages that's why i did not create the image on hub.docker.com, I'm just using docket as a dev environment. :)

**Comment by PatrickHeneise** [comment]
:scream: you don't have node installed??

**Comment by repejota** [comment]
Forcing myself to use docker and learn :sweat_smile:

**Comment by PatrickHeneise** [comment]
how does that work when you make a change? Don't you have to build the container all the time?

**Comment by repejota** [comment]
That's a bit more complex:

If you use Linux you don't need anything more as metalsmith.io sends notify events when a file is modified.
But if you use OSX there is a fucking bug on the vboxfs and those events are not sent. Then, I usually execute something like this:

```
docker run -p 80:3000 -ti --rm -v `pwd`:/barcelonajs barcelonajs bash
```
Which gives me a bash inside the container and I can then execute `node serve.js` every time i change anything on the source code. 
It is not perfect but it works.

I'm experimenting a lot latelly, I have a couple of projects trying to embed a good editor like vim + language_of_choice + docker on a container so I wouldn't need to install anything on my box.
For example for rust: https://github.com/repejota/docker-vim-rust

There's many ways to do the same :)

**Comment by repejota** [comment]
By the way ... we had a talk about Docker for nodejs developers with best practices, tips etc ...?
I could think on prepare something if it is interesting ...

**Comment by PatrickHeneise** [comment]
yeah that's a great idea!

**Comment by PatrickHeneise** [comment]
I personally use docker in deployment, but tbh. I'd never use it for dev and all my projects are set up like this. Everything should just work with `npm run dev` or similar and reload with every code change.

**Pull request merged**
